#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# Merge in resources and keymaps

[ -f $sysresources ]  && xrdb -merge $sysresources
[ -f $userresources ] && xrdb -merge $userresources
[ -f $sysmodmap ]     && xmodmap $sysmodmap
[ -f $usermodmap ]    && xmodmap $usermodmap

# Select an xsession/client

[ -n "`/etc/X11/chooser.sh`" ] && xsession="`/etc/X11/chooser.sh`"

# Load additional configuration

if [ -d /etc/X11/xinit/xinitrc.d ]
then
	for f in /etc/X11/xinit/xinitrc.d/*
	do
		[ -x "$f" ] && source $f
	done
	unset f
fi

# Start the selected xsession/client

if [ -n "$xsession" ]
then
	exec $xsession
else
	xterm -geometry 80x20+0+0 &
	xterm -geometry 80x20-0+0 &
	exec xmessage -center \
"Unable to determine a window manager to start.
Please check your configuration; set $XSESSION.
Closing this window terminates X11."
fi
