#!/bin/sh

case $# in
1)
	case $1 in
	failsafe)
		exec xterm -geometry 80x24-0-0
		;;
	esac
esac

# redirect errors to a file in user's home directory if we can
for errfile in "$HOME/.xsession-errors" "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
do
	if ( cp /dev/null "$errfile" 2> /dev/null )
	then
		chmod 600 "$errfile"
		exec > "$errfile" 2>&1
		break
	fi
done

# clean up after xbanner
which freetemp 2> /dev/null && freetemp

startup=$HOME/.xsession

userresources=$HOME/.Xresources 
usermodmap=$HOME/.Xmodmap 
userxkbmap=$HOME/.Xkbmap

sysresources=/etc/X11/Xresources 
sysmodmap=/etc/X11/Xmodmap 
sysxkbmap=/etc/X11/Xkbmap

rh6sysresources=/etc/X11/xinit/Xresources 
rh6sysmodmap=/etc/X11/xinit/Xmodmap 


# merge in defaults
[ -f "$rh6sysresources" ] && xrdb -merge "$rh6sysresources"
[ -f "$sysresources" ]	  && xrdb -merge "$sysresources"
[ -f "$userresources" ]   && xrdb -merge "$userresources"

# merge in keymaps
if [ -f "$sysxkbmap" ]
then
	setxkbmap `cat "$sysxkbmap"`
	XKB_IN_USE=yes
fi

if [ -f "$userxkbmap" ]
then
	setxkbmap `cat "$userxkbmap"`
	XKB_IN_USE=yes
fi

#
# Eeek, this seems like too much magic here
#
if [ -z "$XKB_IN_USE" -a ! -L /etc/X11/X ]
then
	if grep '^exec.*/Xsun' /etc/X11/X > /dev/null 2>&1 && [ -f /etc/X11/XF86Config ]
	then
	   xkbsymbols=`sed -n -e 's/^[	 ]*XkbSymbols[   ]*"\(.*\)".*$/\1/p' /etc/X11/XF86Config`
	   if [ -n "$xkbsymbols" ]
	   then
		   setxkbmap -symbols "$xkbsymbols"
		   XKB_IN_USE=yes
	   fi
	fi
fi

# xkb and xmodmap don't play nice together
if [ -z "$XKB_IN_USE" ]
then
	[ -f "$rh6sysmodmap" ] && xmodmap "$rh6sysmodmap"
	[ -f "$sysmodmap" ]	   && xmodmap "$sysmodmap"
	[ -f "$usermodmap" ]   && xmodmap "$usermodmap"
fi

unset XKB_IN_USE

if [ -x "$startup" ]
then
	exec "$startup"
elif [ -x "$HOME/.Xclients" ]
then
	exec "$HOME/.Xclients"
elif [ -x /etc/X11/xinit/Xclients ]
then
	exec /etc/X11/xinit/Xclients
elif [ -x /etc/X11/Xclients ]
then
	exec /etc/X11/Xclients
else
	exec xsm
fi
